### ISSUE TITLE
Building on Ubuntu 23.04 with -DCLANGD_ENABLE_REMOTE=On fails with "undefined reference to symbol 'grpc_shutdown'"

### ISSUE THREAD

**Issue by i-ky** [clangd/clangd#1618]
After upgrading from Ubuntu 22.10 to 23.04 I can no longer build clangd from source. Here is how I normally build clangd:
```
cd ~
git clone --depth 1 https://github.com/llvm/llvm-project.git
cd llvm-project/
mkdir build
cd build/
cmake ~/llvm-project/llvm/ -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -G Ninja -DCLANGD_ENABLE_REMOTE=On
cmake --build ~/llvm-project/build --target clangd
```
Of course, I don't do `git clone` every time, usually just `git pull`. I also don't re-configure the project every time, but there was an issue with protobuf header incompatibility, so I had to completely removed build directory and re-configure.

**Logs**

```
[1/1] Linking CXX executable bin/clangd
FAILED: bin/clangd 
: && /usr/bin/c++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG -Wl,-rpath-link,/home/i-ky/llvm-project/build/./lib  -Wl,--gc-sections tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/AddUsing.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/AnnotateHighlightings.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/DumpAST.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/DefineInline.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/DefineOutline.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ExpandDeducedType.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ExpandMacro.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ExtractFunction.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ExtractVariable.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/MemberwiseConstructor.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ObjCLocalizeStringLiteral.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/ObjCMemberwiseInitializer.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/PopulateSwitch.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/RawStringLiteral.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/RemoveUsingNamespace.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/SpecialMembers.cpp.o tools/clang/tools/extra/clangd/refactor/tweaks/CMakeFiles/obj.clangDaemonTweaks.dir/SwapIfBranches.cpp.o tools/clang/tools/extra/clangd/tool/CMakeFiles/clangd.dir/ClangdMain.cpp.o tools/clang/tools/extra/clangd/tool/CMakeFiles/clangd.dir/Check.cpp.o -o bin/clangd  -Wl,-rpath,"\$ORIGIN/../lib:"  lib/libLLVMSupport.a  lib/libLLVMAArch64Info.a  lib/libLLVMAMDGPUInfo.a  lib/libLLVMARMInfo.a  lib/libLLVMAVRInfo.a  lib/libLLVMBPFInfo.a  lib/libLLVMHexagonInfo.a  lib/libLLVMLanaiInfo.a  lib/libLLVMLoongArchInfo.a  lib/libLLVMMipsInfo.a  lib/libLLVMMSP430Info.a  lib/libLLVMNVPTXInfo.a  lib/libLLVMPowerPCInfo.a  lib/libLLVMRISCVInfo.a  lib/libLLVMSparcInfo.a  lib/libLLVMSystemZInfo.a  lib/libLLVMVEInfo.a  lib/libLLVMWebAssemblyInfo.a  lib/libLLVMX86Info.a  lib/libLLVMXCoreInfo.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMOption.a  lib/libLLVMTargetParser.a  lib/libclangAST.a  lib/libclangBasic.a  lib/libclangFormat.a  lib/libclangFrontend.a  lib/libclangLex.a  lib/libclangSema.a  lib/libclangTooling.a  lib/libclangToolingCore.a  lib/libclangToolingRefactoring.a  lib/libclangToolingSyntax.a  lib/libclangTidy.a  lib/libclangDaemon.a  lib/libclangdRemoteIndex.a  lib/libclangdSupport.a  lib/libclangdRemoteIndexServiceProto.a  lib/libclangdMonitoringServiceProto.a  lib/libclangdRemoteMarshalling.a  lib/libclangDaemon.a  lib/libclangToolingSyntax.a  lib/libclangIncludeCleaner.a  lib/libclangToolingInclusionsStdlib.a  lib/libclangPseudo.a  lib/libclangPseudoGrammar.a  lib/libclangTidyAndroidModule.a  lib/libclangTidyAbseilModule.a  lib/libclangTidyAlteraModule.a  lib/libclangTidyBoostModule.a  lib/libclangTidyCERTModule.a  lib/libclangTidyConcurrencyModule.a  lib/libclangTidyDarwinModule.a  lib/libclangTidyFuchsiaModule.a  lib/libclangTidyHICPPModule.a  lib/libclangTidyBugproneModule.a  lib/libclangAnalysisFlowSensitiveModels.a  lib/libclangAnalysisFlowSensitive.a  lib/libclangTidyCppCoreGuidelinesModule.a  lib/libclangTidyGoogleModule.a  lib/libclangTidyLinuxKernelModule.a  lib/libclangTidyLLVMModule.a  lib/libclangTidyLLVMLibcModule.a  lib/libclangTidyMiscModule.a  lib/libclangTidyModernizeModule.a  lib/libclangTidyObjCModule.a  lib/libclangTidyOpenMPModule.a  lib/libclangTidyPerformanceModule.a  lib/libclangTidyPortabilityModule.a  lib/libclangTidyReadabilityModule.a  lib/libclangTidyZirconModule.a  lib/libclangTidyMPIModule.a  lib/libclangTidyUtils.a  lib/libclangTidy.a  lib/libclangTooling.a  lib/libclangStaticAnalyzerFrontend.a  lib/libclangStaticAnalyzerCheckers.a  lib/libclangStaticAnalyzerCore.a  lib/libclangCrossTU.a  lib/libclangTransformer.a  lib/libclangToolingRefactoring.a  lib/libclangIndex.a  lib/libclangFormat.a  lib/libclangToolingInclusions.a  lib/libclangFrontend.a  lib/libclangDriver.a  lib/libLLVMWindowsDriver.a  lib/libclangParse.a  lib/libclangToolingCore.a  lib/libclangRewrite.a  lib/libclangSerialization.a  lib/libclangSema.a  lib/libclangEdit.a  lib/libclangAnalysis.a  lib/libclangSupport.a  lib/libLLVMFrontendHLSL.a  lib/libclangASTMatchers.a  lib/libclangAST.a  lib/libclangLex.a  lib/libclangBasic.a  lib/libclangdSupport.a  lib/libclangdRemoteIndexProto.a  lib/libLLVMAArch64Info.a  lib/libLLVMAMDGPUInfo.a  lib/libLLVMARMInfo.a  lib/libLLVMAVRInfo.a  lib/libLLVMBPFInfo.a  lib/libLLVMHexagonInfo.a  lib/libLLVMLanaiInfo.a  lib/libLLVMLoongArchInfo.a  lib/libLLVMMipsInfo.a  lib/libLLVMMSP430Info.a  lib/libLLVMNVPTXInfo.a  lib/libLLVMPowerPCInfo.a  lib/libLLVMRISCVInfo.a  lib/libLLVMSparcInfo.a  lib/libLLVMSystemZInfo.a  lib/libLLVMVEInfo.a  lib/libLLVMWebAssemblyInfo.a  lib/libLLVMX86Info.a  lib/libLLVMXCoreInfo.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMTransformUtils.a  lib/libLLVMAnalysis.a  lib/libLLVMProfileData.a  lib/libLLVMSymbolize.a  lib/libLLVMDebugInfoPDB.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMObject.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMIRReader.a  lib/libLLVMBitReader.a  lib/libLLVMAsmParser.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMOption.a  lib/libLLVMTargetParser.a  lib/libLLVMSupport.a  -lrt  -ldl  -lm  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libtinfo.so  lib/libLLVMDemangle.a  /usr/lib/x86_64-linux-gnu/libgrpc++.so  /usr/lib/x86_64-linux-gnu/libprotobuf.so && :
/usr/bin/ld: lib/libclangdRemoteIndex.a(Client.cpp.o): undefined reference to symbol 'grpc_shutdown'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgrpc.so.29: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**System information**

Operating system: Ubuntu 23.04

P.S. The issue seems similar to https://github.com/llvm/llvm-project/issues/59844, which had a [fix](https://reviews.llvm.org/D141047) that was later [reverted](https://reviews.llvm.org/rG275bca657529ac07781c5f84e6485fa9d98a1c44). gRPC version is 1.51.1 in my case as well.

**Comment by i-ky** [comment]
I have first experienced this issue on a work computer, but now I have upgraded my personal PC too, so I have all ~~the time in the world~~ my free time to investigate the issue.

It seems that [Ubuntu 22.04 (jammy) was shipping gRPC 1.30.2](https://packages.ubuntu.com/jammy/libgrpc++-dev) and starting with 23.04 (lunar), e.g. in [24.04 (noble)](https://packages.ubuntu.com/noble/libgrpc++-dev), it ships 1.51.1.

GitHub Actions workflow uses 1.36.3 (built from source):
https://github.com/clangd/clangd/blob/ff6fd4914810e0e8693cb45381e45c1cd080c3c5/.github/workflows/autobuild.yaml#L221-L226

So the issue appers somewhere between 1.36.3 and 1.51.1.

**Comment by i-ky** [comment]
I managed to "minimize" the command:
```
/usr/bin/c++ tools/clang/tools/extra/clangd/tool/CMakeFiles/clangd.dir/ClangdToolMain.cpp.o lib/libclangdMain.a lib/libclangdRemoteIndex.a /usr/lib/x86_64-linux-gnu/libgrpc++.so
/usr/bin/ld: lib/libclangdRemoteIndex.a(Client.cpp.o): undefined reference to symbol 'grpc_shutdown'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgrpc.so.29: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Removing any of the arguments chages the output.

**Comment by i-ky** [comment]
I believe the issue has nothing to do with `libgrpc++`, but is related to `bfd` linker. If I force a different linker (e.g. `-fuse-ld=gold`) the output of the command changes. If I add `-Wl,--copy-dt-needed-entries` the output also changes.

I guess that defaults have changed in GCC or `ld` or `bfd` between Ubuntu versions.
