### ISSUE TITLE
Linux CI builds has failed for two weeks

### ISSUE THREAD

**Issue by InfinityWei** [clangd/clangd#2415]
The error is:
```
/__w/clangd/clangd/llvm-project/clang/lib/AST/ItaniumMangle.cpp:4732:16: error: use of overloaded operator '<<' is ambiguous (with operand types 'llvm::raw_svector_ostream' and 'clang::SpirvOperand::SpirvOperandKind')
    TypeNameOS << Operand.getKind();
    ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~
```
From GitHub Actions job's [link](https://github.com/clangd/clangd/actions/runs/15522832649/job/43698347270)

**Comment by InfinityWei** [comment]
Based on the CI build test results from my forks:[log](https://github.com/InfinityWei/clangd/actions/runs/15670240459/job/44140035994). 
It seems that upgrading clang-9 to clang-10 in the Linux CI configuration could resolve the compilation errors.

**Comment by HighCommander4** [comment]
> Based on the CI build test results from my forks:[log](https://github.com/InfinityWei/clangd/actions/runs/15670240459/job/44140035994). It seems that upgrading clang-9 to clang-10 in the Linux CI configuration could resolve the compilation errors.

Thanks for tracking that down! I guess, when we update the ubuntu version used for the build (as we did recently in https://github.com/clangd/clangd/pull/2319), we should also make a corresponding update to the clang compiler version used?

Would you like to submit a PR?

**Comment by InfinityWei** [comment]
OK, I will open a PR. And i have also tested, the linux snapshot version of clangd works well on my Ubuntu 18.04 machine.

**Comment by InfinityWei** [comment]
PR #2416 has submitted.
