### ISSUE TITLE
Weekly snapshot releases are not being published since 20240128

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#1983]
The newest public weekly snapshot release at https://github.com/clangd/clangd/releases is 20240128.

**Comment by HighCommander4** [comment]
Looks like the Windows builds are failing with:

```console
[3045/3051] Building CXX object tools\clang\tools\extra\clangd\index\remote\server\CMakeFiles\clangd-index-server.dir\Server.cpp.obj
FAILED: tools/clang/tools/extra/clangd/index/remote/server/CMakeFiles/clangd-index-server.dir/Server.cpp.obj 
C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DCARES_STATICLIB -DGOOGLE_PROTOBUF_NO_RTTI=1 -DGTEST_HAS_RTTI=0 -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -ID:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\tools\extra\clangd\index\remote\server -ID:\a\clangd\clangd\llvm-project\clang-tools-extra\clangd\index\remote\server -ID:\a\clangd\clangd\llvm-project\clang-tools-extra\clangd\..\include-cleaner\include -ID:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\tools\extra\clangd\..\clang-tidy -ID:\a\clangd\clangd\llvm-project\clang\include -ID:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include -ID:\a\clangd\clangd\clangd_snapshot_20240317\include -ID:\a\clangd\clangd\llvm-project\llvm\include -ID:\a\clangd\clangd\llvm-project\clang-tools-extra\clangd -ID:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\tools\extra\clangd -ID:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\tools\extra\clangd\index\remote -external:IC:\Users\runneradmin\grpc-installation\include -external:W0 /DWIN32 /D_WINDOWS   /Zc:inline /Zc:preprocessor /Zc:__cplusplus /Oi /bigobj /permissive- /W4 -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4351 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd5105 -wd4324 -w14062 -we4238 /Gw /O2 /DNDEBUG -std:c++17 -MT  /EHs-c- /GR- /showIncludes /Fotools\clang\tools\extra\clangd\index\remote\server\CMakeFiles\clangd-index-server.dir\Server.cpp.obj /Fdtools\clang\tools\extra\clangd\index\remote\server\CMakeFiles\clangd-index-server.dir\ /FS -c D:\a\clangd\clangd\llvm-project\clang-tools-extra\clangd\index\remote\server\Server.cpp
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(27): error C2144: syntax error: 'void' should be preceded by '}'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(27): error C2062: type 'void' unexpected
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(40): error C2143: syntax error: missing ';' before '}'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(91): error C2059: syntax error: '}'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(91): error C2143: syntax error: missing ';' before '}'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Frontend/HLSL/HLSLResource.h(19): error C2143: syntax error: missing ';' before '{'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Frontend/HLSL/HLSLResource.h(19): error C2447: '{': missing function header (old-style formal list?)
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5306): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5306): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5306): error C3646: 'resourceClass': unknown override specifier
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5306): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5309): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5315): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5315): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5315): error C2061: syntax error: identifier 'ResourceClass'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5316): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5316): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5316): error C2061: syntax error: identifier 'ResourceClass'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5317): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5317): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5317): error C2061: syntax error: identifier 'ResourceClass'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5317): error C2143: syntax error: missing ')' before '{'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5317): error C2535: 'clang::HLSLResourceAttr *clang::HLSLResourceAttr::CreateImplicit(clang::ASTContext &)': member function already defined or declared
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5315): note: see declaration of 'clang::HLSLResourceAttr::CreateImplicit'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5317): error C2059: syntax error: ')'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5318): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5318): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5318): error C2061: syntax error: identifier 'ResourceClass'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5318): error C2143: syntax error: missing ')' before '{'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5318): error C2535: 'clang::HLSLResourceAttr *clang::HLSLResourceAttr::Create(clang::ASTContext &)': member function already defined or declared
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5316): note: see declaration of 'clang::HLSLResourceAttr::Create'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5318): error C2059: syntax error: ')'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5322): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5322): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5321): error C2061: syntax error: identifier 'ResourceClass'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5327): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5327): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5326): error C2061: syntax error: identifier 'ResourceClass'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5326): error C2535: 'clang::HLSLResourceAttr::HLSLResourceAttr(clang::ASTContext &,const clang::AttributeCommonInfo &)': member function already defined or declared
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5321): note: see declaration of 'clang::HLSLResourceAttr::HLSLResourceAttr'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5335): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5335): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5335): error C3646: 'getResourceClass': unknown override specifier
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5335): error C2059: syntax error: '('
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5335): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5339): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5339): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5339): error C2061: syntax error: identifier 'ResourceClass'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5340): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5340): error C2039: 'ResourceClass': is not a member of 'llvm'
D:\a\clangd\clangd\llvm-project\llvm\include\llvm/Support/DXILABI.h(22): note: see declaration of 'llvm'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5340): error C2061: syntax error: identifier 'ResourceClass'
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5341): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5345): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
D:\a\clangd\clangd\clangd_snapshot_20240317\tools\clang\include\clang/AST/Attrs.inc(5346): error C3083: 'hlsl': the symbol to the left of a '::' must be a type
```

**Comment by HighCommander4** [comment]
Looks like potentially a regression from https://github.com/llvm/llvm-project/pull/78224.

@bogner, any chance you could take a look at the compiler error above (seems to be related to an enumerator named `VOID` getting macro-expanded to `void` and triggering syntax errors) and advise how we might resolve it?

**Comment by bogner** [comment]
The enumerator named `VOID` isn't new - that change simply renamed the file it was defined in. Is it possible something changed in the environment as well? Where is `VOID` being defined as a macro?

**Comment by bogner** [comment]
note: I'm not opposed to changing the spelling of the `ParameterKind` values if it helps - it's an unusual style choice to make them all caps anyway. However, I don't see how the change in question could have caused this issue.

**Comment by HighCommander4** [comment]
> Where is `VOID` being defined as a macro?

I don't have a Windows environment around to confirm, but based on some searching around it's likely [winnt.h](https://stackoverflow.com/questions/6669078/purpose-of-uppercase-void-macro-int-typedef-in-winnt-h).

> The enumerator named `VOID` isn't new - that change simply renamed the file it was defined in. Is it possible something changed in the environment as well?

Yeah, good point. I guess the actual regressing change was something around the same time that introduced a new transitive #include of that file into a file which also includes winnt.h.

**Comment by HighCommander4** [comment]
Snapshot releases are now working again (I triggered one today manually at https://github.com/clangd/clangd/releases/tag/snapshot_20240327).

Thank you @bogner for fixing the Windows build issue!
