### ISSUE TITLE
`ninja check-clangd` fails with protobuf-related errors on recent trunk

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#1599]
With a recent trunk, while the `clangd` and `ClangdTests` targets build successfully for me, building the `check-clangd` target fails with the following errors:

```console
$ ninja check-clangd
[7/9] Building CXX object tools/clang/tools/extra/clangd/index/remote/monitor/CMakeFiles/clangd-index-server-monitor.dir/Monitor.cpp.o
FAILED: tools/clang/tools/extra/clangd/index/remote/monitor/CMakeFiles/clangd-index-server-monitor.dir/Monitor.cpp.o
CCACHE_CPP2=yes CCACHE_HASHDIR=yes /usr/bin/ccache /usr/bin/clang++-15 -DGOOGLE_PROTOBUF_NO_RTTI=1 -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D_LIBCPP_ENABLE_ASSERTIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/nr/dev/projects/llvm/build/tools/clang/tools/extra/clangd/index/remote/monitor -I/home/nr/dev/projects/llvm/src/clang-tools-extra/clangd/index/remote/monitor -I/home/nr/dev/projects/llvm/src/clang-tools-extra/clangd/../include-cleaner/include -I/home/nr/dev/projects/llvm/build/tools/clang/tools/extra/clangd/../clang-tidy -I/home/nr/dev/projects/llvm/src/clang/include -I/home/nr/dev/projects/llvm/build/tools/clang/include -I/home/nr/dev/projects/llvm/build/include -I/home/nr/dev/projects/llvm/src/llvm/include -I/home/nr/dev/projects/llvm/src/clang-tools-extra/clangd -I/home/nr/dev/projects/llvm/build/tools/clang/tools/extra/clangd -I/home/nr/dev/projects/llvm/build/tools/clang/tools/extra/clangd/index/remote -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O0 -g3  -fno-exceptions -funwind-tables -fno-rtti -std=c++17 -MD -MT tools/clang/tools/extra/clangd/index/remote/monitor/CMakeFiles/clangd-index-server-monitor.dir/Monitor.cpp.o -MF tools/clang/tools/extra/clangd/index/remote/monitor/CMakeFiles/clangd-index-server-monitor.dir/Monitor.cpp.o.d -o tools/clang/tools/extra/clangd/index/remote/monitor/CMakeFiles/clangd-index-server-monitor.dir/Monitor.cpp.o -c /home/nr/dev/projects/llvm/src/clang-tools-extra/clangd/index/remote/monitor/Monitor.cpp
/home/nr/dev/projects/llvm/src/clang-tools-extra/clangd/index/remote/monitor/Monitor.cpp:71:53: error: no member named 'code' in 'google::protobuf::util::Status'
                        static_cast<int>(JsonStatus.code()),
                                         ~~~~~~~~~~ ^
/home/nr/dev/projects/llvm/src/clang-tools-extra/clangd/index/remote/monitor/Monitor.cpp:72:36: error: no member named 'message' in 'google::protobuf::util::Status'
                        JsonStatus.message().as_string());
                        ~~~~~~~~~~ ^
2 errors generated.
ninja: build stopped: subcommand failed
```

I did a clean build to rule out something being incorrectly cached from a previous build.

Any ideas as to what may be going wrong?

**Edit**: I'm building with `-DCLANGD_ENABLE_REMOTE=ON` which seems to be relevant to the error.

**Comment by HighCommander4** [comment]
I guess it's caused by https://reviews.llvm.org/D144599.

cc @MatzeB

**Comment by HighCommander4** [comment]
If building with `-DCLANGD_ENABLE_REMOTE=ON` requires a certain minimum version of gRPC, shouldn't this be checked at CMake time, and an error issued if the installed gRPC version is too low?

**Comment by HighCommander4** [comment]
Also, what _is_ the minimum required gRPC version? I upgraded from 1.16 to 1.30, and now I'm getting even more errors... is 1.30 still too old?

**Comment by i-ky** [comment]
> Is 1.30 still too old?

I am using official Ubuntu package, it comes with 1.30.2:
```
$ apt list *gRPC*
...
libgrpc++-dev/kinetic,now 1.30.2-3build6 amd64 [installed]
...
```
I added `--target check-clangd` to my build command for a test and it succeeded. But I have to say that I do `cmake --build ...` instead of invoking `ninja` directly.

**Comment by HighCommander4** [comment]
Ok, I filed #1603 for the errors I'm getting trying to build with 1.30.

**Comment by HighCommander4** [comment]
I'll close this since I can't reproduce #1603 any more (and the original issue was presumably fixed by the upgrade from 1.16 to 1.30).
